name: Build

on:
  push:
    branches:
      - main

  # Run tests for any PRs.
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build PDF
        run: |
          docker run --mount src=$PWD,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic curriculum.tex"

      - name: Generate artifact for PDF
        uses: actions/upload-artifact@v2
        with:
          name: Alin_Sorin_Nedelcu_CV.pdf
          path: curriculum.pdf
