name: Compile (Tectonic)

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build PDF
        run: |
          docker run --mount src=$PWD,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "apk add ttf-font-awesome; tectonic --keep-intermediates --reruns 0 biber-mwe.tex; biber biber-mwe; tectonic Alin_Sorin_Nedelcu_CV.tex; tectonic Alin_Sorin_Nedelcu_CV-ES.tex"

      - name: Generate artifact for PDF (default)
        uses: actions/upload-artifact@v2
        with:
          name: Alin_Sorin_Nedelcu_CV.pdf
          path: Alin_Sorin_Nedelcu_CV.pdf

      - name: Generate artifact for PDF (spanish)
        uses: actions/upload-artifact@v2
        with:
          name: Alin_Sorin_Nedelcu_CV-ES.pdf
          path: Alin_Sorin_Nedelcu_CV-ES.pdf
